# To enable graphiql
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
# To enable graphql metrics
graphql:
  servlet:
    actuator-metrics: true
# To enable to get metrics of spring-actuator from /actuator/prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
